apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  labels:
    app: global-config
data:
  appsettings.json: |
    {
      "database": {
        "provider": "redis",
        "url":"localhost",
        "port":6379
      },
      "cache": {
        "provider": "redis",
        "url":"localhost",
        "port":6379
      }
    }